services:
  kf-task-fhir-etl:
    image: kf-task-fhir-etl:${GIT_COMMIT:-latest}
    build: 
        context: . 
        dockerfile: Dockerfile

  terraform:
    build: ./deployment
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-chopd3bprod}
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - GIT_COMMIT
      - ETL_SETTINGS_BUCKET=${ETL_SETTINGS_BUCKET}
    working_dir: /usr/local/src
    entrypoint: bash
